{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: ecommerce-lite
spec:
  serviceName: mongodb
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.service.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ROOT_USER
                  optional: true
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_ROOT_PASSWORD
                  optional: true
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          livenessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mongodb.storage.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.mongodb.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None   # headless for StatefulSet DNS
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
      name: mongo
{{- end }}
